version: '3.8'
services:
  dev-database:
    image: postgres:16.2
    container_name: dev-database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app_db
    networks:
      - nestjs-network
networks:
  nestjs-network:


#version: '3.8'
#services:
#  mysql:
#    image: mysql:8.0
#    volumes:
#      - mysqldb:/var/lib/mysql
#    environment:
#      MYSQL_DATABASE: app_db
#      MYSQL_ROOT_PASSWORD: secret
#      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
#    ports:
#      - "3306:3306"
#    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
#
#volumes:
#  mysqldb:
#    driver: local
